import os
import io
import re
from flask import Flask, render_template, request, send_file, jsonify
import google.generativeai as genai
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# Configure Gemini
GENAI_API_KEY = os.getenv("GEMINI_API_KEY")
genai.configure(api_key=GENAI_API_KEY)

def clean_text(text):
    # Remove bold/italic markdown
    text = text.replace('**', '').replace('__', '').replace('##', '')
    # Remove potential duplicate headers generated by AI
    lines = text.split('\n')
    cleaned_lines = []
    for line in lines:
        # Skip lines that look like headers we already have
        if "Time:" in line or "Max Marks:" in line or "Class:" in line:
            continue
        cleaned_lines.append(line)
    return "\n".join(cleaned_lines).strip()

def generate_paper_content(subject, book, chapters, difficulty, grade, time, marks, prompt_text):
    model = genai.GenerativeModel('gemini-pro')
    
    full_prompt = f"""
    Create a strictly formatted CBSE Class {grade} Exam Question Paper.
    
    Subject: {subject}
    Book: {book}
    Chapters: {chapters}
    Difficulty: {difficulty}
    Time: {time}
    Max Marks: {marks}
    
    Instructions: {prompt_text}
    
    STRICT OUTPUT FORMAT:
    1. Do NOT include the School Name, Subject Name, Time, or Max Marks at the top (I have a separate header for that).
    2. Start immediately with "General Instructions:" followed by a numbered list of instructions suitable for a {marks} marks paper.
    3. Then write "SECTION A", "SECTION B", etc. centered.
    4. Number questions as "1.", "2.", etc.
    5. Put marks in brackets at the end of every question, e.g. "(1)", "(3)".
    6. Ensure the questions are relevant to: {chapters}.
    """
    
    response = model.generate_content(full_prompt)
    return clean_text(response.text)

def create_word_doc(header_info, content):
    doc = Document()
    
    # Base Style
    style = doc.styles['Normal']
    style.font.name = 'Times New Roman'
    style.font.size = Pt(11)

    # --- 1. SCHOOL HEADER (Centered) ---
    def add_header_line(text, size=11, bold=False, italic=False):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(text)
        run.bold = bold
        run.italic = italic
        run.font.size = Pt(size)
        p.paragraph_format.space_after = Pt(0) # Tight spacing

    add_header_line("BHARATIYA VIDYA BHAVAN’S RESIDENTIAL PUBLIC SCHOOL", 14, True)
    add_header_line("(Sponsored by rice millers’ education and cultural society, W.G.Dt)", 10)
    add_header_line("VIDHYASHRAM – BHIMAVARAM-534201", 12, True)
    doc.add_paragraph() # Spacer

    add_header_line(f"{header_info['test_name']} – {header_info['academic_year']}", 12, True)

    # --- 2. METADATA TABLE ---
    table = doc.add_table(rows=2, cols=2)
    table.autofit = True
    
    # Row 1
    table.cell(0, 0).text = f"Sub: {header_info['subject']}"
    cell_r1 = table.cell(0, 1)
    cell_r1.text = f"Time: {header_info['time']}"
    cell_r1.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

    # Row 2
    table.cell(1, 0).text = f"Class: {header_info['grade']}"
    cell_r2 = table.cell(1, 1)
    cell_r2.text = f"Max Marks: {header_info['marks']}"
    cell_r2.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
    
    # Bold the table text
    for row in table.rows:
        for cell in row.cells:
            for p in cell.paragraphs:
                for run in p.runs:
                    run.bold = True
                    run.font.name = 'Times New Roman'

    doc.add_paragraph("_" * 90).alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph() 

    # --- 3. QUESTION CONTENT (Left Aligned) ---
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        p = doc.add_paragraph()
        
        # Check for Section Headers (Center them)
        if line.upper().startswith("SECTION") or line.upper().startswith("PART") or "GENERAL INSTRUCTIONS" in line.upper():
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(line)
            run.bold = True
            run.font.size = Pt(12)
            p.paragraph_format.space_before = Pt(12)
        else:
            # Regular Questions (Left Aligned)
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            p.add_run(line)

    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    try:
        text = generate_paper_content(
            data.get('subject'),
            data.get('book'),
            data.get('chapters'),
            data.get('difficulty'),
            data.get('grade'),
            data.get('time'),
            data.get('marks'),
            data.get('prompt')
        )
        return jsonify({'success': True, 'content': text})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

@app.route('/download', methods=['POST'])
def download():
    data = request.form
    header_info = {
        'subject': data.get('subject'),
        'grade': data.get('grade'),
        'test_name': data.get('testName'),
        'academic_year': data.get('year'),
        'time': data.get('time'),
        'marks': data.get('marks')
    }
    content = data.get('content')
    
    file_stream = create_word_doc(header_info, content)
    
    return send_file(
        file_stream,
        as_attachment=True,
        download_name=f"{data.get('subject')}_Exam_Paper.docx",
        mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)
